AWSTemplateFormatVersion: '2010-09-09'
Description: 'trip

  Rest API to manage Trips

  '
Globals:
  Function:
    MemorySize: 512
    Timeout: 20
Outputs:
  CreateTripRecordFunction:
    Description: CreateTripRecord Lambda Function ARN
    Value:
      Fn::GetAtt:
      - CreateTripRecordFunction
      - Arn
  GetTripRecordsByCountryFunction:
    Description: GetTripRecordsByCountry Lambda Function ARN
    Value:
      Fn::GetAtt:
      - GetTripRecordsByCountryFunction
      - Arn
  GetTripRecordsByPeriodFunction:
    Description: GetTripRecordsByPeriod Lambda Function ARN
    Value:
      Fn::GetAtt:
      - GetTripRecordsByPeriodFunction
      - Arn
  GetTripRecordsByCityFunction:
    Description: GetTripRecordsByCity Lambda Function ARN
    Value:
      Fn::GetAtt:
      - GetTripRecordsByCityFunction
      - Arn
Resources:
  CreateTripRecordFunction:
    Properties:
      CodeUri: s3://aws-sam-fiap-deployt/896a140ec24d1c84f917b82d6bdddd3f
      Events:
        CreateTripRecord:
          Properties:
            Method: post
            Path: /trip
          Type: Api
      Handler: br.com.trip.handler.CreateTripRecord::handleRequest
      Runtime: java8
    Type: AWS::Serverless::Function
  GetTripRecordsByCountryFunction:
    Properties:
      CodeUri: s3://aws-sam-fiap-deployt/896a140ec24d1c84f917b82d6bdddd3f
      Events:
        GetTripRecordsByCountry:
          Properties:
            Method: get
            Path: /trip/{country}
            RequestParameters:
            - method.request.querystring.country
          Type: Api
      Handler: br.com.trip.handler.GetTripRecordsByCountry::handleRequest
      Runtime: java8
    Type: AWS::Serverless::Function
  GetTripRecordsByPeriodFunction:
    Properties:
      CodeUri: s3://aws-sam-fiap-deployt/896a140ec24d1c84f917b82d6bdddd3f
      Events:
        GetTripRecordsByPeriod:
          Properties:
            Method: get
            Path: /trip/findByPeriod
            RequestParameters:
            - method.request.querystring.start
            - method.request.querystring.end
          Type: Api
      Handler: br.com.trip.handler.GetTripRecordsByPeriod::handleRequest
      Runtime: java8
    Type: AWS::Serverless::Function
  GetTripRecordsByCityFunction:
    Properties:
      CodeUri: s3://aws-sam-fiap-deployt/896a140ec24d1c84f917b82d6bdddd3f
      Events:
        GetTripRecordsByCity:
          Properties:
            Method: get
            Path: /trip/{country}/findByCity
            RequestParameters:
            - method.request.querystring.city
          Type: Api
      Handler: br.com.trip.handler.GetTripRecordsByCity::handleRequest
      Runtime: java8
    Type: AWS::Serverless::Function
Transform: AWS::Serverless-2016-10-31
